name: Fetch ISS TLE

on:
  schedule:
    - cron: '0 1-23/6 * * *'  # Starts at 1 AM UTC and runs every 6 hours
  workflow_dispatch:  # Allow manual triggering if needed

jobs:
  fetch-tle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run TLE Fetch Script
        run: |
          python scripts/fetch_tle.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add iss_tle.json
          git commit -m "Update ISS TLE"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
